# ---- Base Node ----
FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
RUN npm install
COPY . .
RUN npm run build
RUN rm -rf node_modules
RUN npm install --only=production

# ---- Release ----
FROM node:20-alpine AS release
WORKDIR /app
COPY --from=dependencies /app/dist ./dist
COPY --from=dependencies /app/node_modules ./node_modules
COPY package*.json ./
EXPOSE 8000
CMD ["node", "dist/main"]